# Чтож, пришло время делать конфиги!1!!
"version": 3

# Защита карты от вандалов
protect-world: false

# Запрещает игрокам преступать черту. Значение `radius: 0` отключает ограничение.
"world-limit":
 "radius": 500
 "x": 0
 "z": 0

# точка спавна во всех мирах. Если нуль, то она не изменится.
"spawn-point":
 "x": null
 "y": null
 "z": null
