# Чтож, пришло время делать конфиги!1!!
"version": 6

# Защита карты от вандалов
protect-world: false

# Запрещает игрокам преступать черту. Значение `radius: 0` отключает ограничение.
"world-limit":
 "radius": 500
 "x": 0
 "z": 0

# Точка спавна во всех мирах. Если нуль, то она не изменится.
"spawn-point":
 "x": null
 "y": null
 "z": null

# Телепортировать на спавн при выходе?
"alwaysOnSpawn": false
# Начислять деньги за время в игре?
"time-fee": true

# Адреса серверов для телепортации к ним
servers:
 -
  ip: "rivex.online"
  port: 19132
  name: "Hub"
  transfer: false
  portal: false
 -
  ip: "rivex.online"
  port: 19131
  name: "Survival"
  transfer: true
  portal:
   "x": 0
   "y": 0
   "z": 0
   "radius": 4
